
project_id = "cyzpqzvrssgamdtqvyze"

[functions.generate-ai-response]
verify_jwt = false

[functions.process-policy-document]
verify_jwt = false

[functions.fetch-url-content]
verify_jwt = false

[functions.analyze-legislation-impact]
verify_jwt = false

[functions.fetch-mapbox-token]
verify_jwt = false
