// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyzpqzvrssgamdtqvyze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5enBxenZyc3NnYW1kdHF2eXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjU3NDMsImV4cCI6MjA1OTcwMTc0M30.sQq-QxaqZaeTBttYMJgGjdQhGAFcrNL8P4qIQb_klyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);